### ISSUE TITLE
letsencrypt support requires manual action

### ISSUE THREAD

**Issue by msherman64** [ChameleonCloud/chi-in-a-box#116]
Letsencrypt support currently requires manually requesting the first certificate.

This is because enabling letsencrypt support tells haproxy to use the TLS certificate, but letsencrypt runs after haproxy, and uses it for public access.

Therefore, enabling it only works if you already have a valid cert configured!

Currently, you can run the process manually, in this order.
1. Run deploy with letsencrypt disabled
2. use docker exec -it letsencrypt_certbot bash to manually run certbot
3. copy certificate out to site-config/certificates folder
4. enable letsencrypt, and re-run deploy.

**Comment by super-cooper** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automate TLS certificate renewal for CHI-in-a-box sites](https://trello.com/c/nyJl1B03/2795-automate-tls-certificate-renewal-for-chi-in-a-box-sites)

**Comment by msherman64** [comment]
Since we backported upstream's letsencypt integration, this is now resolved.
https://github.com/ChameleonCloud/chi-in-a-box/commit/925fc4737ca8b833da9f5a9b05de9ea631ab3dd8
