### ISSUE TITLE
LetsEncrypt certificate renewal does not automatically reload HAProxy

### ISSUE THREAD

**Issue by diurnalist** [ChameleonCloud/chi-in-a-box#125]
Certs are being renewed properly, but HAProxy is never notified, so it is still possible for the cert to expire from the end-user's point of view unless care is taken to periodically poke HAProxy.

**Comment by super-cooper** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automate Portal TLS certificate renewal](https://trello.com/c/UjaGiLvr/2790-automate-portal-tls-certificate-renewal)

**Comment by super-cooper** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automate TLS certificate renewal for CHI-in-a-box sites](https://trello.com/c/nyJl1B03/2795-automate-tls-certificate-renewal-for-chi-in-a-box-sites)

**Comment by super-cooper** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automate TLS certificate renewal for CHI-in-a-box sites](https://trello.com/c/nyJl1B03/2795-automate-tls-certificate-renewal-for-chi-in-a-box-sites)

**Comment by super-cooper** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automate TLS certificate renewal for CHI-in-a-box sites](https://trello.com/c/nyJl1B03/2795-automate-tls-certificate-renewal-for-chi-in-a-box-sites)
