### ISSUE TITLE
Module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by samiemostafavi** [ChameleonCloud/chi-in-a-box#220]
I faced this error several times during the installation. For example after running `./cc-ansible init --site /opt/site-config`. 
The solution is easy:

`
source venv/bin/activate && pip3 install pyOpenSSL --upgrade
`

It seems to be due to pip upgrade. Upgrade pyOpenSSL to 22.0.0 to fix the issue.

Best,
Samie

**Comment by msherman64** [comment]
What base OS are you using, and what version of pyOpenSSL was installed before and after your command was run?

I haven't observed this issue yet at current sites deploying on Ubuntu 20.04.

**Comment by samiemostafavi** [comment]
I am using Ubuntu server 20.04, before the upgrade pyOpenSSL version is 19.0.0, after the upgrade it is 22.1.0.
I tested on another machine today.

**Comment by msherman64** [comment]
Are you able to replicate the issue after running the following?

```
cd /opt/chi-in-a-box # or whatever the path is to your git checkout
rm -rf venv
./cc-ansible init --site /opt/site-config
```

My guess is that your venv is in an inconsistent state. If that doesn't resolve the issue, it could be that the venv is created with `--system-site-packages`, and there's a conflicting package version installed on the system level.

Outside the venv, can you run `pip show pyOpenSSL`?

**Comment by samiemostafavi** [comment]
I run the command in a completely clean state where there is no venv.
However when I run `pip show pyOpenSSL` I get the 19.0.0 version.

**Comment by msherman64** [comment]
Thanks for the info. I was able to replicate the issue starting from an upstream ubuntu 20.04.5 image, working on adding a fix.
