### ISSUE TITLE
[heat] heat_auth_encryption_key must be 32 chars...

### ISSUE THREAD

**Issue by wehall** [ChameleonCloud/chi-in-a-box#269]
heat_engine container doesn't start due to heat_auth_encryption_key exceeding 32 chars.
As workaround/fix, truncate generated hash to 32 chars via cc-ansible edit_passwords.

**Comment by msherman64** [comment]
This is a very late reply, but this is now fixed both in xena and 2023.1.
see: https://github.com/ChameleonCloud/kolla-ansible/commit/9f2f8653fe55d5cbd0f7f432dda0526660073f55

to apply the fix to an existing site, exactly your workaround is appropriate.
