### ISSUE TITLE
Certificate copy fails with --site is a relative path

### ISSUE THREAD

**Issue by diurnalist** [ChameleonCloud/chi-in-a-box#78]
When the --site param is a relative path, the certificate copy fails. This seems to be because --site is used as `node_config`. We may need to capture this param and turn it in to an absolute path:

```
TASK [haproxy : Copying over haproxy.pem] ************ failed:
[development] (item=/etc/kolla/haproxy/certs.d/haproxy.pem) => 
{"ansible_loop_var": "item", "changed": false, "item": "/etc/kolla/haproxy/certs.d/haproxy.pem", 
"msg": "Could not find or access './site-config/certificates/haproxy.pem...
```

**Comment by ariscahyadi** [comment]
@diurnalist, I hope that I am not the only one who is facing this problem :)

Also, in the case of chameleon standalone installation, can you give an example of how to generate this certificate? such as "self-signed" certificate for a testing purpose :)

**Comment by diurnalist** [comment]
@ariscahyadi the [Kolla-Ansible docs](https://docs.openstack.org/kolla-ansible/latest/admin/advanced-configuration.html) have a section on self-signed certificate generation that may be useful. You would invoke it like:

```
./cc-ansible certificates
```

That "cc-ansible" script is mostly a wrapper for kolla-ansible that does some special stuff, like install dependencies and set a few variable overrides.

**Comment by ariscahyadi** [comment]
Thanks, @diurnalist ... I will look into it.
